### PR TITLE
build: bump semantic-release to 17.3.9 to address dependabot alert

### PR DESCRIPTION
**Pull request by a6software**
## Ticket Number
UCD-1697

## Description of change
bump semantic-release to 17.3.9 to address dependabot alert - https://github.com/foundry4/appeal-planning-decision/security/dependabot/package-lock.json/marked/open

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [ ] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

### CODE REVIEW

**Review by Fenisay — APPROVED** [review]

**Comment by a6software** [comment]
close, unwanted

**Comment by marcfielding1** [comment]
I'm not sure this is unwanted, an outdated package shouldn't ever be ignored I don't think regardless of what it's *currently* used for. Can you reopen?

**Comment by MrSimonEmms** [comment]
@marcfielding1 this isn't really used in the source code. Semantic Release is used to generate the version numbers from the commit messages, so it never goes anywhere near the production code - it's a dev dependency only

**Comment by marcfielding1** [comment]
@MrSimonEmms Yeah I do understand that, I guess my point would be if we're delivering software to the client and dependency that's way of date sends the wrong message - also whilst *this* dep likely won't cause us any issues if we adopt that as a policy then eventually it could happen that we get outdated deps creeping in.

I do agree with you, but I disagree that we shouldn't fix it because it's outdated.

**Pull request closed without merging**
