### PR TITLE
chore: promote versions to preprod for demo

### PR DESCRIPTION
**Pull request by frank-dodion**
## Ticket Number
UCD-1606

## Description of change
Promote versions to preprod for demo

### CODE REVIEW

**Review by MrSimonEmms — DISMISSED** [review]
No, that won't work. You need to update the semver in the annotations at the top of the file

**Comment by frank-dodion** [comment]
> No, that won't work. You need to update the semver in the annotations at the top of the file

How about this?

**Review by MrSimonEmms — DISMISSED** [review]
Looks better. Remove the changes in the `tag` (that will get done for you) and combine the three commits as per the rebase wiki please

**Comment by frank-dodion** [comment]
> Looks better. Remove the changes in the `tag` (that will get done for you) and combine the three commits as per the rebase wiki please

Don't that.

**Comment by MrSimonEmms** [comment]
There's still three commits. Rebase and squash the commits as per the wiki

**Review by MrSimonEmms — APPROVED** [review]

**Pull request merged**
