### PR TITLE
Subtask/ucd 1692 glue code for horizon queue

### PR DESCRIPTION
**Pull request by a6software**
## Ticket Number

UCD-1692

## Description of change
glue code for horizon queue

## Checklist

- [ ] Requires infrastructure changes
- [ ] If adding or remove environment variables (e.g. in `docker-compose.yaml`) then I have updated the appropriate Helm chart
- [ ] I have updated the documentation accordingly
- [ ] My commit history in this PR is linear
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

### CODE REVIEW

**Comment by a6software** [comment]
Seems very much dependant on https://github.com/foundry4/appeal-planning-decision/pull/509

**Review by danWatkinson — APPROVED** [review]
we need to sort out the business of asserting against the payload on the queue, but i think we know that's a thing we will do once everything is in the feature branch, so approving this so we can merge+get on with that

**Comment by a6software** [comment]
Pushed up the very latest changes, but am aware this is super brittle. Covers the very specific AC set.

**Review by danWatkinson — COMMENTED** [review]
happy enough with the glue code
totally see what you mean about it being fragile + specific but i totally agree it's the way to get this story over the line today

**Review by MrSimonEmms — APPROVED** [review]

**Pull request merged**
