### PR TITLE
fix(decision-date): rebrand planning authority into planning department

### PR DESCRIPTION
**Pull request by Fenisay**
Huge PR

### CODE REVIEW

**Review by a6software — COMMENTED** [review]
just checking, It Was Capitalised Before, is it ok now to be lower case ?

**Comment by MrSimonEmms** [comment]
@a6software dunno. Imagine that Ed is probably the chap to check with

**Comment by MrSimonEmms** [comment]
It's lowercase on https://www.gov.uk/planning-permission-england-wales

**Comment by Fenisay** [comment]
> just checking, It Was Capitalised Before, is it ok now to be lower case ?

Yep, that's normal but thanks for asking !

**Review by MrSimonEmms — APPROVED** [review]

**Comment by Fenisay** [comment]
> It's lowercase on https://www.gov.uk/planning-permission-england-wales
> 
> image

in fact it changed many times but this US was not updated. From now on I will stick to the prototype (which also changed :p)

**Comment by Fenisay** [comment]
Thanks

**Pull request merged**
