### PR TITLE
Mongo updates from MS call

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Ticket Number

UCD-891

## Description of change

Updates to MongoDB instance following call with Microsoft
 - write failover
 - zone redundancy

## Checklist

- [ ] Requires infrastructure changes
- [ ] I have updated the documentation accordingly
- [x] I have merged commits to avoid fixing things in this PR
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

### CODE REVIEW

**Review by frank-dodion — DISMISSED** [review]
Looks OK as I far as I can tell without sight of the infrastructure. I couldn't help thinking, "Wouldn't it be nice to have Mongo as a service?"

**Comment by MrSimonEmms** [comment]
> Looks OK as I far as I can tell without sight of the infrastructure. I couldn't help thinking, "Wouldn't it be nice to have Mongo as a service?"

We do have Mongo as a service. It's all configured in the `mongo.tf` file

**Comment by frank-dodion** [comment]
> > Looks OK as I far as I can tell without sight of the infrastructure. I couldn't help thinking, "Wouldn't it be nice to have Mongo as a service?"
> 
> We do have Mongo as a service. It's all configured in the `mongo.tf` file

I meant a service that is highly available etc automatically so we don't have to manage that.

**Comment by MrSimonEmms** [comment]
@frank-dodion yeah, that's exactly what this is. This configures CosmosDB (and MongoDB underneath that)

**Comment by frank-dodion** [comment]
> > > Looks OK as I far as I can tell without sight of the infrastructure. I couldn't help thinking, "Wouldn't it be nice to have Mongo as a service?"
> > 
> > 
> > We do have Mongo as a service. It's all configured in the `mongo.tf` file
> 
> I meant a service that is highly available etc automatically so we don't have to manage that.

Got it.

**Comment by frank-dodion** [comment]
> @frank-dodion yeah, that's exactly what this is. This configures CosmosDB (and MongoDB underneath that)

Got it.

**Review by frank-dodion — APPROVED** [review]

**Review by frank-dodion — APPROVED** [review]

**Pull request merged**
