### PR TITLE
feat(e2e-tests): update applicant name feature

### PR DESCRIPTION
**Pull request by Fenisay**
UCD-1159

### CODE REVIEW

**Review by MrSimonEmms — COMMENTED** [review]
Based on the fact that this is just changing a test file (and not the published source code), arguably this should be a `chore` or `test` commit, not a `feat`.

**Comment by danWatkinson** [comment]
i would say that if we're hoping to accumulate the whole story in this PR rather than just the test-changes.. the statement re: feature/chore may or may not be valid..
in this instance i think i agree: the net result should be parity, so this is really a refactoring excercise/chore that just happens to include some test-tweaking to make sure that we -would- catch any problems we created in the rest of the change.

other opinions are available.

**Review by a6software — APPROVED** [review]
Approving on the basis the code looks fine.

**Review by danWatkinson — APPROVED** [review]
looks good

**Pull request merged**
