### PR TITLE
test(e2e-tests): add of site ownership step definitions

### PR DESCRIPTION
**Pull request by Fenisay**
UCD-888

### CODE REVIEW

**Review by karunak21 — CHANGES_REQUESTED** [review]
Line 14, 20: Should start with: And the user can see that the appeal ....

**Review by karunak21 — COMMENTED** [review]
Feature Description: 
Prospective appellant asked to notify the owners of the appeal site where necessary

**Comment by Fenisay** [comment]
> Line 14, 20: Should start with: And the user can see that the appeal ....

Yes it's done I changed this part from the feature file already merged

**Comment by Fenisay** [comment]
> Line 14, 20: Should start with: And the user can see that the appeal ....

Ok I get it, it's fixed thanks

**Comment by a6software** [comment]
Just checking before review - should this be failing cypress due to new FF stuff?

**Comment by Fenisay** [comment]
> Just checking before review - should this be failing cypress due to new FF stuff?

I needed to pipe the glue code and the code, didn't expect to have it right at first run ( I did not) but yes now there is changes in FF that I'll need to do so don't bother with any kind of review at the moment !

**Review by a6software — APPROVED** [review]

**Review by frank-dodion — APPROVED** [review]
Looks good

**Pull request merged**
